window.lessons = {
	/* stare początek */
    0: {
        label: 'Pedagogika ogólna: 15 w',
        color: '#F49AC2',
        hours: [
            {group: 1, day: 1, time: 5, place: 0, duration: 1, teacher: 0},
            {group: 2, day: 1, time: 5, place: 0, duration: 2, teacher: 0},
            {group: 3, day: 1, time: 6, place: 0, duration: 1, teacher: 0},
            {group: 4, day: 1, time: 6, place: 0, duration: 2, teacher: 0},
        ]
    },
	/* stare koniec */
	/* nowe początek */
    0: {
        label: 'Pedagogika ogólna: 15 w Isem',
        color: '#F49AC2',
		duration: 1,
        hours: [
            {group: 1, day: 1, time: 5, place: 0, duration: 1, teacher: 0},
            {group: 3, day: 1, time: 6, place: 0, duration: 1, teacher: 0},
        ]
    },
    1: {
        label: 'Pedagogika ogólna: 15 w IIsem',
        color: '#F49AC2',
		duration: 2,
        hours: [
            {group: 2, day: 1, time: 5, place: 0, duration: 2, teacher: 0},
            {group: 4, day: 1, time: 6, place: 0, duration: 2, teacher: 0},
        ]
    },
	/* nowe koniec */
    2: {
        label: 'Pedagogika ogólna: 30 k',
        color: '#779ECB',
        hours: [
            {group: 1, day: 1, time: 2, place: 2, teacher: 1},
            {group: 2, day: 1, time: 3, place: 2, teacher: 1},
            {group: 3, day: 1, time: 4, place: 2, teacher: 1},
            {group: 4, day: 2, time: 3, place: 2, teacher: 1},
            {group: 5, day: 4, time: 3, place: 0, teacher: 0},
            {group: 6, day: 4, time: 4, place: 0, teacher: 0},
            {group: 7, day: 4, time: 5, place: 0, teacher: 0},
            {group: 8, day: 3, time: 4, place: 0, teacher: 0},
            {group: 9, day: 3, time: 5, place: 0, teacher: 0},
            {group: 10, day: 3, time: 6, place: 0, teacher: 0},
            {group: 11, day: 4, time: 2, place: 0, teacher: 0},
            {group: 12, day: 2, time: 4, place: 2, teacher: 0},
            {group: 13, day: 2, time: 5, place: 2, teacher: 0},
            {group: 14, day: 2, time: 6, place: 2, teacher: 0},
            {group: 15, day: 3, time: 5, place: 2, teacher: 2},
            {group: 16, day: 2, time: 0, place: 2, teacher: 3},
            {group: 17, day: 2, time: 1, place: 2, teacher: 3},
            {group: 18, day: 2, time: 2, place: 2, teacher: 3},
            {group: 19, day: 2, time: 3, place: 2, teacher: 3},
            {group: 20, day: 2, time: 2, place: 2, teacher: 3},
            {group: 21, day: 2, time: 3, place: 2, teacher: 3},
            {group: 22, day: 3, time: 6, place: 2, teacher: 2},
            {group: 23, day: 4, time: 0, place: 2, teacher: 4},
            {group: 24, day: 4, time: 2, place: 2, teacher: 4},
            {group: 25, day: 4, time: 3, place: 2, teacher: 4},
            {group: 26, day: 4, time: 4, place: 2, teacher: 4},
        ]
    },
	/* nowe początek */
    4: {
        label: 'Podstawy rozwoju biologicznego człowieka :15 w',
        color: '#C23B22',
		duration: 1,
        hours: [
            {group: 1, day: 1, time: 0, place: 1, teacher: 5},
            {group: 3, day: 1, time: 1, place: 1, teacher: 5},
        ]
    },
    5: {
        label: 'Podstawy rozwoju biologicznego człowieka :15 w',
        color: '#C23B22',
		duration: 2,
        hours: [
            {group: 2, day: 1, time: 0, place: 1, teacher: 5},
            {group: 4, day: 1, time: 1, place: 1, teacher: 5},
        ]
    },
	/* nowe koniec */
    6: {
        label: 'Podstawy rozwoju biologicznego człowieka :15 k',
        color: '#FDFD96',
        hours: [
            {group: 1, day: 1, time: 1, place: 0, duration: 1, teacher: 5},
            {group: 2, day: 1, time: 1, place: 0, duration: 2, teacher: 5},
            {group: 3, day: 1, time: 2, place: 0, duration: 1, teacher: 5},
            {group: 4, day: 4, time: 0, place: 2, duration: 1, teacher: 5},
            {group: 5, day: 4, time: 0, place: 2, duration: 2, teacher: 5},
            {group: 6, day: 4, time: 1, place: 2, duration: 1, teacher: 5},
            {group: 7, day: 4, time: 1, place: 2, duration: 2, teacher: 5},
            {group: 8, day: 4, time: 2, place: 2, duration: 1, teacher: 5},
            {group: 9, day: 4, time: 2, place: 2, duration: 2, teacher: 5},
            {group: 10, day: 4, time: 3, place: 2, duration: 1, teacher: 5},
            {group: 11, day: 4, time: 3, place: 2, duration: 2, teacher: 5},
            {group: 12, day: 3, time: 3, place: 2, duration: 1, teacher: 6},
            {group: 13, day: 3, time: 3, place: 2, duration: 2, teacher: 6},
            {group: 14, day: 3, time: 5, place: 2, duration: 1, teacher: 6},
            {group: 15, day: 3, time: 5, place: 2, duration: 2, teacher: 6},
            {group: 16, day: 3, time: 6, place: 2, duration: 1, teacher: 6},
            {group: 17, day: 2, time: 0, place: 2, duration: 2, teacher: 7},
            {group: 18, day: 2, time: 1, place: 2, duration: 2, teacher: 7},
            {group: 19, day: 2, time: 2, place: 2, duration: 2, teacher: 7},
            {group: 20, day: 2, time: 3, place: 2, duration: 1, teacher: 7},
            {group: 21, day: 2, time: 4, place: 2, duration: 1, teacher: 7},
            {group: 22, day: 2, time: 5, place: 2, duration: 1, teacher: 7},
            {group: 23, day: 2, time: 0, place: 2, duration: 2, teacher: 7},
            {group: 24, day: 2, time: 1, place: 2, duration: 2, teacher: 7},
            {group: 25, day: 1, time: 5, place: 2, duration: 2, teacher: 7},
            {group: 26, day: 1, time: 6, place: 2, duration: 2, teacher: 7},
        ]
    },
    8: {
        label: 'Socjologia- 15 w',
        color: '#966FD6',
        hours: [
            {group: 1, day: 4, time: 3, place: 0, duration: 2, teacher: 8},
            {group: 2, day: 1, time: 3, place: 0, duration: 1, teacher: 9},
            {group: 3, day: 4, time: 2, place: 0, duration: 2, teacher: 8},
            {group: 4, day: 1, time: 4, place: 0, duration: 2, teacher: 9},
        ]
    },
    10: {
        label: 'Socjologia- 15 k',
        color: '#DEA5A4',
        hours: [
            {group: 1, day: 1, time: 4, place: 0, duration: 1, teacher: 10},
            {group: 2, day: 1, time: 5, place: 0, duration: 1, teacher: 10},
            {group: 3, day: 1, time: 5, place: 0, duration: 2, teacher: 10},
            {group: 4, day: 2, time: 3, place: 0, duration: 1, teacher: 10},
            {group: 5, day: 2, time: 3, place: 0, duration: 2, teacher: 10},
            {group: 6, day: 2, time: 4, place: 0, duration: 1, teacher: 10},
            {group: 7, day: 2, time: 4, place: 0, duration: 2, teacher: 10},
            {group: 8, day: 1, time: 0, place: 0, duration: 1, teacher: 9},
            {group: 9, day: 1, time: 0, place: 0, duration: 2, teacher: 9},
            {group: 10, day: 1, time: 1, place: 0, duration: 1, teacher: 9},
            {group: 11, day: 1, time: 4, place: 0, duration: 1, teacher: 9},
            {group: 12, day: 1, time: 2, place: 0, duration: 1, teacher: 9},
            {group: 13, day: 1, time: 2, place: 0, duration: 2, teacher: 9},
            {group: 14, day: 2, time: 2, place: 0, duration: 2, teacher: 9},
            {group: 15, day: 2, time: 3, place: 0, duration: 2, teacher: 9},
            {group: 16, day: 2, time: 4, place: 0, duration: 1, teacher: 9},
            {group: 17, day: 2, time: 4, place: 0, duration: 2, teacher: 9},
            {group: 18, day: 4, time: 0, place: 0, duration: 1, teacher: 9},
            {group: 19, day: 4, time: 1, place: 0, duration: 1, teacher: 9},
            {group: 20, day: 4, time: 2, place: 0, duration: 1, teacher: 9},
            {group: 21, day: 2, time: 0, place: 2, duration: 1, teacher: 11},
            {group: 22, day: 2, time: 0, place: 2, duration: 2, teacher: 11},
            {group: 23, day: 2, time: 0, place: 2, duration: 1, teacher: 12},
            {group: 24, day: 2, time: 1, place: 2, duration: 1, teacher: 12},
            {group: 25, day: 2, time: 3, place: 0, duration: 2, teacher: 13},
            {group: 26, day: 2, time: 4, place: 0, duration: 2, teacher: 13},
        ]
    },
    12: {
        label: 'Historia wychowania -30w',
        color: '#B19CD9',
        hours: [
            {group: 1, day: 1, time: 1, place: 0, teacher: 14},
            {group: 2, day: 2, time: 1, place: 0, teacher: 15},
            {group: 3, day: 2, time: 4, place: 0, teacher: 16},
            {group: 4, day: 1, time: 0, place: 0, teacher: 15},
        ]
    },
    14: {
        label: 'Historia wychowania -30 k',
        color: '#FFD1DC',
        hours: [
            {group: 1, day: 2, time: 3, place: 2, teacher: 17},
            {group: 2, day: 2, time: 4, place: 2, teacher: 17},
            {group: 3, day: 2, time: 3, place: 0, teacher: 16},
            {group: 4, day: 1, time: 2, place: 0, teacher: 16},
            {group: 5, day: 1, time: 3, place: 0, teacher: 16},
            {group: 6, day: 1, time: 4, place: 0, teacher: 16},
            {group: 7, day: 2, time: 2, place: 2, teacher: 18},
            {group: 8, day: 2, time: 3, place: 2, teacher: 18},
            {group: 9, day: 2, time: 4, place: 2, teacher: 18},
            {group: 10, day: 2, time: 0, place: 2, teacher: 18},
            {group: 11, day: 2, time: 1, place: 2, teacher: 18},
            {group: 12, day: 2, time: 2, place: 2, teacher: 18},
            {group: 13, day: 1, time: 3, place: 0, teacher: 14},
            {group: 14, day: 2, time: 3, place: 2, teacher: 14},
            {group: 15, day: 2, time: 4, place: 2, teacher: 14},
            {group: 16, day: 2, time: 2, place: 2, teacher: 19},
            {group: 17, day: 2, time: 3, place: 2, teacher: 19},
            {group: 18, day: 2, time: 4, place: 0, teacher: 18},
            {group: 19, day: 2, time: 2, place: 2, teacher: 17},
            {group: 20, day: 2, time: 0, place: 2, teacher: 20},
            {group: 21, day: 2, time: 1, place: 2, teacher: 20},
        ]
    },
    16: {
        label: 'Filozofia: 15 w',
        color: '#CB99C9',
        hours: [
            {group: 1, day: 2, time: 5, place: 0, duration: 1, teacher: 21},
            {group: 2, day: 2, time: 5, place: 0, duration: 2, teacher: 21},
            {group: 3, day: 2, time: 6, place: 0, duration: 1, teacher: 21},
            {group: 4, day: 2, time: 6, place: 0, duration: 2, teacher: 21},
        ]
    },
    18: {
        label: 'Filozofia: 15 k',
        color: '#B39EB5',
        hours: [
            {group: 1, day: 1, time: 4, place: 2, duration: 1, teacher: 22},
            {group: 2, day: 2, time: 4, place: 2, duration: 2, teacher: 22},
            {group: 3, day: 2, time: 5, place: 2, duration: 1, teacher: 22},
            {group: 4, day: 3, time: 3, place: 2, duration: 1, teacher: 22},
            {group: 5, day: 3, time: 3, place: 2, duration: 2, teacher: 22},
            {group: 6, day: 3, time: 4, place: 2, duration: 1, teacher: 22},
            {group: 7, day: 3, time: 4, place: 2, duration: 2, teacher: 22},
            {group: 8, day: 3, time: 5, place: 2, duration: 1, teacher: 22},
            {group: 9, day: 3, time: 5, place: 2, duration: 2, teacher: 22},
            {group: 10, day: 0, time: 0, place: 2, duration: 2, teacher: 23},
            {group: 11, day: 1, time: 1, place: 2, duration: 2, teacher: 23},
            {group: 12, day: 1, time: 2, place: 2, duration: 2, teacher: 23},
            {group: 13, day: 2, time: 4, place: 0, duration: 1, teacher: 23},
            {group: 14, day: 2, time: 4, place: 0, duration: 2, teacher: 23},
            {group: 15, day: 3, time: 4, place: 2, duration: 1, teacher: 24},
            {group: 16, day: 3, time: 4, place: 2, duration: 1, teacher: 24},
            {group: 17, day: 3, time: 5, place: 2, duration: 1, teacher: 24},
            {group: 18, day: 3, time: 5, place: 2, duration: 2, teacher: 24},
            {group: 19, day: 3, time: 6, place: 2, duration: 1, teacher: 24},
            {group: 20, day: 3, time: 6, place: 2, duration: 2, teacher: 24},
            {group: 21, day: 0, time: 1, place: 2, duration: 1, teacher: 24},
            {group: 22, day: 1, time: 1, place: 2, duration: 2, teacher: 24},
            {group: 23, day: 2, time: 5, place: 2, duration: 2, teacher: 22},
            {group: 24, day: 1, time: 5, place: 0, duration: 1, teacher: 25},
            {group: 25, day: 2, time: 2, place: 2, duration: 1, teacher: 26},
            {group: 26, day: 2, time: 2, place: 2, duration: 2, teacher: 26},
        ]
    },
    20: {
        label: 'Psychologia ogólna:15 w',
        color: '#FFB347',
        hours: [
            {group: 1, day: 1, time: 1, place: 0, duration: 2, teacher: 27},
            {group: 2, day: 1, time: 2, place: 0, duration: 2, teacher: 27},
            {group: 3, day: 1, time: 3, place: 0, duration: 2, teacher: 27},
            {group: 4, day: 1, time: 1, place: 0, duration: 1, teacher: 27},
        ]
    },
    22: {
        label: 'Psychologia ogólna: 30 k',
        color: '#AEC6CF',
        hours: [
            {group: 1, day: 3, time: 4, place: 0, teacher: 28},
            {group: 2, day: 3, time: 5, place: 0, teacher: 28},
            {group: 3, day: 4, time: 1, place: 2, teacher: 29},
            {group: 4, day: 4, time: 2, place: 2, teacher: 29},
            {group: 5, day: 4, time: 0, place: 0, teacher: 30},
            {group: 6, day: 2, time: 5, place: 2, teacher: 31},
            {group: 7, day: 2, time: 6, place: 2, teacher: 31},
            {group: 8, day: 3, time: 5, place: 0, teacher: 32},
            {group: 9, day: 3, time: 6, place: 0, teacher: 32},
            {group: 10, day: 4, time: 3, place: 2, teacher: 29},
            {group: 11, day: 4, time: 0, place: 0, teacher: 33},
            {group: 12, day: 4, time: 1, place: 0, teacher: 33},
            {group: 13, day: 4, time: 2, place: 0, teacher: 33},
            {group: 14, day: 4, time: 3, place: 0, teacher: 33},
            {group: 15, day: 4, time: 0, place: 2, teacher: 32},
            {group: 16, day: 4, time: 1, place: 2, teacher: 32},
            {group: 17, day: 2, time: 1, place: 2, teacher: 27},
            {group: 18, day: 3, time: 5, place: 0, teacher: 33},
            {group: 19, day: 3, time: 6, place: 0, teacher: 33},
            {group: 20, day: 2, time: 5, place: 0, teacher: 33},
            {group: 21, day: 2, time: 6, place: 0, teacher: 33},
        ]
    },
    24: {
        label: 'Psychologia ogólna: 15 k',
        color: '#836953',
        hours: [
            {group: 1, day: 2, time: 0, place: 2, duration: 2, teacher: 27},
            {group: 2, day: 2, time: 2, place: 0, duration: 1, teacher: 27},
            {group: 3, day: 2, time: 3, place: 0, duration: 1, teacher: 27},
            {group: 4, day: 2, time: 0, place: 2, duration: 1, teacher: 27},
        ]
    },
    26: {
        label: 'Warsztat komunikacji interpersonalnej: 15 k',
        color: '#FF6961',
        hours: [
            {group: 1, day: 1, time: 0, place: 0, duration: 1, teacher: 34},
            {group: 2, day: 1, time: 1, place: 0, duration: 1, teacher: 34},
            {group: 3, day: 1, time: 1, place: 0, duration: 2, teacher: 34},
            {group: 4, day: 4, time: 1, place: 2, duration: 1, teacher: 35},
            {group: 5, day: 4, time: 0, place: 0, duration: 2, teacher: 36},
            {group: 6, day: 4, time: 1, place: 0, duration: 2, teacher: 36},
            {group: 7, day: 2, time: 5, place: 0, duration: 2, teacher: 37},
            {group: 8, day: 2, time: 6, place: 0, duration: 2, teacher: 37},
            {group: 9, day: 2, time: 6, place: 0, duration: 2, teacher: 37},
            {group: 10, day: 4, time: 0, place: 2, duration: 1, teacher: 38},
            {group: 11, day: 4, time: 0, place: 2, duration: 2, teacher: 38},
            {group: 12, day: 4, time: 1, place: 2, duration: 1, teacher: 38},
            {group: 13, day: 0, time: 0, place: 2, duration: 1, teacher: 39},
            {group: 14, day: 4, time: 1, place: 2, duration: 2, teacher: 38},
            {group: 15, day: 0, time: 2, place: 2, duration: 2, teacher: 32},
            {group: 16, day: 4, time: 1, place: 2, duration: 2, teacher: 35},
            {group: 17, day: 4, time: 2, place: 2, duration: 1, teacher: 35},
            {group: 18, day: 4, time: 2, place: 2, duration: 2, teacher: 35},
            {group: 19, day: 4, time: 3, place: 2, duration: 1, teacher: 35},
            {group: 20, day: 4, time: 3, place: 2, duration: 2, teacher: 35},
            {group: 21, day: 1, time: 1, place: 2, duration: 1, teacher: 39},
            {group: 22, day: 1, time: 1, place: 0, duration: 2, teacher: 39},
            {group: 23, day: 2, time: 5, place: 0, duration: 2, teacher: 37},
            {group: 24, day: 1, time: 5, place: 0, duration: 2, teacher: 37},
            {group: 25, day: 3, time: 5, place: 0, duration: 2, teacher: 37},
            {group: 26, day: 3, time: 6, place: 0, duration: 2, teacher: 37},
        ]
    },
    28: {
        label: 'Etyka: 15 w',
        color: '#77DD77',
        hours: [
            {group: 1, day: 0, time: 2, place: 1, duration: 2, teacher: 40},
            {group: 2, day: 0, time: 3, place: 1, duration: 2, teacher: 40},
            {group: 3, day: 0, time: 4, place: 1, duration: 2, teacher: 40},
            {group: 4, day: 0, time: 3, place: 1, duration: 1, teacher: 41},
        ]
    },
    30: {
        label: 'Etyka: 15 k',
        color: '#03C03C',
        hours: [
            {group: 1, day: 0, time: 2, place: 2, duration: 1, teacher: 42},
            {group: 2, day: 4, time: 3, place: 2, duration: 2, teacher: 43},
            {group: 3, day: 0, time: 3, place: 2, duration: 1, teacher: 42},
            {group: 4, day: 0, time: 3, place: 2, duration: 2, teacher: 42},
            {group: 5, day: 0, time: 4, place: 2, duration: 1, teacher: 42},
            {group: 6, day: 0, time: 4, place: 2, duration: 2, teacher: 42},
            {group: 7, day: 0, time: 2, place: 2, duration: 2, teacher: 41},
            {group: 8, day: 0, time: 3, place: 2, duration: 2, teacher: 41},
            {group: 9, day: 0, time: 4, place: 2, duration: 2, teacher: 41},
            {group: 10, day: 0, time: 5, place: 2, duration: 2, teacher: 41},
            {group: 11, day: 0, time: 6, place: 2, duration: 2, teacher: 41},
            {group: 12, day: 0, time: 1, place: 2, duration: 2, teacher: 41},
            {group: 13, day: 4, time: 1, place: 2, duration: 1, teacher: 40},
            {group: 14, day: 4, time: 1, place: 2, duration: 2, teacher: 40},
            {group: 15, day: 4, time: 2, place: 2, duration: 1, teacher: 40},
            {group: 16, day: 4, time: 2, place: 2, duration: 2, teacher: 40},
            {group: 17, day: 4, time: 3, place: 2, duration: 1, teacher: 40},
            {group: 18, day: 0, time: 0, place: 2, duration: 2, teacher: 41},
            {group: 19, day: 1, time: 4, place: 2, duration: 1, teacher: 41},
            {group: 20, day: 1, time: 5, place: 2, duration: 1, teacher: 41},
            {group: 21, day: 1, time: 6, place: 2, duration: 1, teacher: 41},
        ]
    }
};